### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [inakleinbottle/texoutparse#1]
kbriggs> python3 try_texoutparse_00.py
Traceback (most recent call last):
  File "py/try_texoutparse_00.py", line 8, in <module>
    parser.process(f)
  File "/usr/local/lib/python3.6/dist-packages/texoutparse.py", line 117, in process
    for i, line in enumerate(lines_iterable):
  File "/usr/local/lib/python3.6/dist-packages/texoutparse.py", line 49, in __next__
    self.current = current = next(self.iterable)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 4821: invalid continuation byte

**Comment by kmccurley** [comment]
The problem is almost certainly due to the fact that a tex log file need not have a single character encoding. I have seen examples where the log file contains a mixture of OT1 and UTF-8 encodings. The best way to parse is probably to use an encoding of UTF-8 with an error handler to replace characters that cannot be decoded.
